FROM debian:jessie
MAINTAINER Naoaki Obiki

RUN apt-get update && apt-get install -y sudo git supervisor

#include "./include/git-daemon.docker"

#include "./include/apt-php.docker"

#include "./include/composer.docker"
#include "./include/satis.docker"

#include "./include/nginx.docker"

COPY bootstrap.sh /
RUN chmod +x /bootstrap.sh

CMD ["/bootstrap.sh"]
