FROM debian:jessie
MAINTAINER Naoaki Obiki

RUN apt-get update && apt-get install -y git

#include "./include/git-daemon.docker"

#include "./include/lamp-php.docker"
#include "./include/composer.docker"
#include "./include/satis.docker"

COPY bootstrap.sh /
RUN chmod +x /bootstrap.sh

CMD ["/bootstrap.sh"]
